### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by alexyarosh** [alexyarosh/hyperbolic#1]
- [ ] PACKAGIFY

- [x]  add `AverageBettis.jl`

- [x] add the sampling notebook

- [ ] add the computing&plotting notebook

- [ ] add error messages for non-supported curvatures 
- [ ] add error messages for non-symmetric matrices
- [ ] standardize function signatures
- [ ] add the data processing `jl` (not sure if need this?)
- [ ] add citations
- [ ] write actual docs
- [x] add support for v.1.0 in `GeometricSampling.jl`

- [ ] change plotting functions to recipes
